version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"  # Spremenjeno iz "27017:27017" na "27018:27017"
    volumes:
      - mongodb_data:/data/db

  users-service:
    image: quarkus/users-jvm
    container_name: users-service
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/usersdb
    ports:
      - "9002:9002"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
