name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017


    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Test with Maven
        run: mvn -B test --file pom.xml
        env:
          QUARKUS_MONGODB_CONNECTION_STRING: mongodb://localhost:27017/usersdb
